# Generated by Django 5.1.3 on 2025-06-11 18:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aichatsession_choice_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='user_profile',
            field=models.JSONField(default=core.models.get_default_user_profile),
        ),
    ]
